# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 grommunio GmbH
# static branding assets
location = /brand/brand.css {
    root /run/grommunio-brand;
    default_type text/css;
    expires -1;
    try_files $uri @brand_none;
}
location = /brand/brand.json {
    root /run/grommunio-brand;
    expires -1;
    try_files $uri =404;
}
location ^~ /brand/ {
    root /run/grommunio-brand;
    access_log off;
    expires 7d;
    try_files $uri =404;
}
location @brand_none {
    default_type text/css;
    return 200 "";
}
