#!/bin/bash
# update/extend grommunio postfix settings as part of grommunio-update

FORCE=false
[ "$1" = '-f' ] && FORCE=true

# Get mysql connection information from either an already configured file in
# postfix and otherwise from gromox's mysql_adaptor in case we deleted it to
# forcibly recreate them instead of using the "-f" switch.
if [ -e /etc/postfix/grommunio-virtual-mailbox-domains.cf ]; then
	MYSQL_USER=$(awk -F'^user = ' '/^user/ { print $2 }' /etc/postfix/grommunio-virtual-mailbox-domains.cf)
	MYSQL_PASS=$(awk -F'^password = ' '/^password/ { print $2 }' /etc/postfix/grommunio-virtual-mailbox-domains.cf)
	MYSQL_HOST=$(awk -F'^hosts = ' '/^hosts/ { print $2 }' /etc/postfix/grommunio-virtual-mailbox-domains.cf)
	MYSQL_DB=$(awk -F'^dbname = ' '/^dbname/ { print $2 }' /etc/postfix/grommunio-virtual-mailbox-domains.cf)
elif [ -e /etc/gromox/mysql_adaptor.cfg ]; then
	MYSQL_CFG="/etc/gromox/mysql_adaptor.cfg"
	MYSQL_USER=$(sed -ne 's/^mysql_username\s*=\s*\(.*\)/\1/p' ${MYSQL_CFG})
	if [ -z "$MYSQL_USER" ]; then
		MYSQL_USER="root"
	fi
	MYSQL_PASS=$(sed -ne 's/^mysql_password\s*=\s*\(.*\)/\1/p' ${MYSQL_CFG})
	MYSQL_DB=$(sed -ne 's/^mysql_dbname\s*=\s*\(.*\)/\1/p' ${MYSQL_CFG})
	if [ -z "$MYSQL_DB" ]; then
		MYSQL_DB="grommunio"
	fi
	if [ "${MYSQL_DB:0:1}" = "-" ]; then
		echo "Cannot use that dbname: ${MYSQL_DB}"
		exit 1
	fi
	MYSQL_HOST=$(sed -ne 's/^mysql_host\s*=\s*\(.*\)/-h\1/p' ${MYSQL_CFG})
	if [ -z "$MYSQL_HOST" ]; then
		MYSQL_HOST="localhost"
	fi
else
	echo "Can not find any MYSQL Connection information" >&2
	exit 1
fi

# update base config grommunio-virtual-mailbox-domains.cf (query might have changed)

if [ $FORCE ] || [ ! -e /etc/postfix/grommunio-virtual-mailbox-domains.cf ]; then
	cat > /etc/postfix/grommunio-virtual-mailbox-domains.cf <<EOF
user = ${MYSQL_USER}
password = ${MYSQL_PASS}
hosts = ${MYSQL_HOST}
dbname = ${MYSQL_DB}
query = SELECT 1 FROM domains WHERE domain_status=0 AND domainname=_utf8mb4'%s' COLLATE utf8mb4_general_ci
EOF

postconf -e virtual_mailbox_domains="mysql:/etc/postfix/grommunio-virtual-mailbox-domains.cf"

fi

# update/extend other postfix configs which have been extended over the time (grommunio-setup)

if [ $FORCE ] || [ ! -e /etc/postfix/grommunio-virtual-mailbox-alias-maps.cf ]; then

	cat > /etc/postfix/grommunio-virtual-mailbox-alias-maps.cf <<EOF
user = ${MYSQL_USER}
password = ${MYSQL_PASS}
hosts = ${MYSQL_HOST}
dbname = ${MYSQL_DB}
query = SELECT mainname FROM aliases WHERE aliasname=_utf8mb4'%s' COLLATE utf8mb4_general_ci UNION SELECT destination FROM forwards WHERE username=_utf8mb4'%s' COLLATE utf8mb4_general_ci AND forward_type = 1
EOF

postconf -e virtual_alias_maps="mysql:/etc/postfix/grommunio-virtual-mailbox-alias-maps.cf"

fi

if [ $FORCE ] || [ ! -e /etc/postfix/grommunio-virtual-mailbox-maps.cf ]; then

	cat > /etc/postfix/grommunio-virtual-mailbox-maps.cf <<EOF
user = ${MYSQL_USER}
password = ${MYSQL_PASS}
hosts = ${MYSQL_HOST}
dbname = ${MYSQL_DB}
query = SELECT 1 FROM users WHERE username=_utf8mb4'%s' COLLATE utf8mb4_general_ci
EOF

postconf -e virtual_mailbox_maps="mysql:/etc/postfix/grommunio-virtual-mailbox-maps.cf"

fi

if [ $FORCE ] || [ ! -e /etc/postfix/grommunio-bcc-forwards.cf ]; then

	cat > /etc/postfix/grommunio-bcc-forwards.cf <<EOF
user = ${MYSQL_USER}
password = ${MYSQL_PASS}
hosts = ${MYSQL_HOST}
dbname = ${MYSQL_DB}
query = SELECT destination FROM forwards WHERE username=_utf8mb4'%s' COLLATE utf8mb4_general_ci AND forward_type = 0
EOF

postconf -e recipient_bcc_maps="mysql:/etc/postfix/grommunio-bcc-forwards.cf"

fi
